package POJOs;
// Generated Feb 4, 2016 8:25:00 PM by Hibernate Tools 4.3.1



/**
 * AdminAccessRight generated by hbm2java
 */
public class AdminAccessRight  implements java.io.Serializable {


     private Integer idAccessRight;
     private AdminAccess adminAccess;
     private Administrator administrator;

    public AdminAccessRight() {
    }

    public AdminAccessRight(AdminAccess adminAccess, Administrator administrator) {
       this.adminAccess = adminAccess;
       this.administrator = administrator;
    }
   
    public Integer getIdAccessRight() {
        return this.idAccessRight;
    }
    
    public void setIdAccessRight(Integer idAccessRight) {
        this.idAccessRight = idAccessRight;
    }
    public AdminAccess getAdminAccess() {
        return this.adminAccess;
    }
    
    public void setAdminAccess(AdminAccess adminAccess) {
        this.adminAccess = adminAccess;
    }
    public Administrator getAdministrator() {
        return this.administrator;
    }
    
    public void setAdministrator(Administrator administrator) {
        this.administrator = administrator;
    }




}


