package POJOs;
// Generated Feb 4, 2016 8:25:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Administrator generated by hbm2java
 */
public class Administrator  implements java.io.Serializable {


     private Integer idadministrator;
     private String adminFname;
     private String adminMname;
     private String adminLname;
     private Set users = new HashSet(0);
     private Set adminAccessRights = new HashSet(0);

    public Administrator() {
    }

    public Administrator(String adminFname, String adminMname, String adminLname, Set users, Set adminAccessRights) {
       this.adminFname = adminFname;
       this.adminMname = adminMname;
       this.adminLname = adminLname;
       this.users = users;
       this.adminAccessRights = adminAccessRights;
    }
   
    public Integer getIdadministrator() {
        return this.idadministrator;
    }
    
    public void setIdadministrator(Integer idadministrator) {
        this.idadministrator = idadministrator;
    }
    public String getAdminFname() {
        return this.adminFname;
    }
    
    public void setAdminFname(String adminFname) {
        this.adminFname = adminFname;
    }
    public String getAdminMname() {
        return this.adminMname;
    }
    
    public void setAdminMname(String adminMname) {
        this.adminMname = adminMname;
    }
    public String getAdminLname() {
        return this.adminLname;
    }
    
    public void setAdminLname(String adminLname) {
        this.adminLname = adminLname;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }
    public Set getAdminAccessRights() {
        return this.adminAccessRights;
    }
    
    public void setAdminAccessRights(Set adminAccessRights) {
        this.adminAccessRights = adminAccessRights;
    }




}


