package POJOs;
// Generated Feb 4, 2016 8:25:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AdminAccess generated by hbm2java
 */
public class AdminAccess  implements java.io.Serializable {


     private Integer idadminAccess;
     private String accessComp;
     private Set adminAccessRights = new HashSet(0);

    public AdminAccess() {
    }

    public AdminAccess(String accessComp, Set adminAccessRights) {
       this.accessComp = accessComp;
       this.adminAccessRights = adminAccessRights;
    }
   
    public Integer getIdadminAccess() {
        return this.idadminAccess;
    }
    
    public void setIdadminAccess(Integer idadminAccess) {
        this.idadminAccess = idadminAccess;
    }
    public String getAccessComp() {
        return this.accessComp;
    }
    
    public void setAccessComp(String accessComp) {
        this.accessComp = accessComp;
    }
    public Set getAdminAccessRights() {
        return this.adminAccessRights;
    }
    
    public void setAdminAccessRights(Set adminAccessRights) {
        this.adminAccessRights = adminAccessRights;
    }




}


