package POJOs;
// Generated Feb 4, 2016 8:25:00 PM by Hibernate Tools 4.3.1



/**
 * Appointment generated by hbm2java
 */
public class Appointment  implements java.io.Serializable {


     private Integer idappointment;
     private Doctor doctor;
     private Patient patient;
     private String appointmentDate;
     private String appointmentTime;

    public Appointment() {
    }

	
    public Appointment(Doctor doctor, Patient patient) {
        this.doctor = doctor;
        this.patient = patient;
    }
    public Appointment(Doctor doctor, Patient patient, String appointmentDate, String appointmentTime) {
       this.doctor = doctor;
       this.patient = patient;
       this.appointmentDate = appointmentDate;
       this.appointmentTime = appointmentTime;
    }
   
    public Integer getIdappointment() {
        return this.idappointment;
    }
    
    public void setIdappointment(Integer idappointment) {
        this.idappointment = idappointment;
    }
    public Doctor getDoctor() {
        return this.doctor;
    }
    
    public void setDoctor(Doctor doctor) {
        this.doctor = doctor;
    }
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }
    public String getAppointmentDate() {
        return this.appointmentDate;
    }
    
    public void setAppointmentDate(String appointmentDate) {
        this.appointmentDate = appointmentDate;
    }
    public String getAppointmentTime() {
        return this.appointmentTime;
    }
    
    public void setAppointmentTime(String appointmentTime) {
        this.appointmentTime = appointmentTime;
    }




}


