package POJOs;
// Generated Feb 4, 2016 8:25:00 PM by Hibernate Tools 4.3.1



/**
 * BlogImages generated by hbm2java
 */
public class BlogImages  implements java.io.Serializable {


     private int idblogImages;
     private Blog blog;
     private String blogImage;

    public BlogImages() {
    }

	
    public BlogImages(int idblogImages, Blog blog) {
        this.idblogImages = idblogImages;
        this.blog = blog;
    }
    public BlogImages(int idblogImages, Blog blog, String blogImage) {
       this.idblogImages = idblogImages;
       this.blog = blog;
       this.blogImage = blogImage;
    }
   
    public int getIdblogImages() {
        return this.idblogImages;
    }
    
    public void setIdblogImages(int idblogImages) {
        this.idblogImages = idblogImages;
    }
    public Blog getBlog() {
        return this.blog;
    }
    
    public void setBlog(Blog blog) {
        this.blog = blog;
    }
    public String getBlogImage() {
        return this.blogImage;
    }
    
    public void setBlogImage(String blogImage) {
        this.blogImage = blogImage;
    }




}


