package POJOs;
// Generated Feb 4, 2016 8:25:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * BlogCaptions generated by hbm2java
 */
public class BlogCaptions  implements java.io.Serializable {


     private int idblogCaptions;
     private Blog blog;
     private User user;
     private String comment;
     private Set blogReplies = new HashSet(0);

    public BlogCaptions() {
    }

	
    public BlogCaptions(int idblogCaptions, Blog blog, User user) {
        this.idblogCaptions = idblogCaptions;
        this.blog = blog;
        this.user = user;
    }
    public BlogCaptions(int idblogCaptions, Blog blog, User user, String comment, Set blogReplies) {
       this.idblogCaptions = idblogCaptions;
       this.blog = blog;
       this.user = user;
       this.comment = comment;
       this.blogReplies = blogReplies;
    }
   
    public int getIdblogCaptions() {
        return this.idblogCaptions;
    }
    
    public void setIdblogCaptions(int idblogCaptions) {
        this.idblogCaptions = idblogCaptions;
    }
    public Blog getBlog() {
        return this.blog;
    }
    
    public void setBlog(Blog blog) {
        this.blog = blog;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Set getBlogReplies() {
        return this.blogReplies;
    }
    
    public void setBlogReplies(Set blogReplies) {
        this.blogReplies = blogReplies;
    }




}


