package POJOs;
// Generated Feb 4, 2016 8:25:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Blog generated by hbm2java
 */
public class Blog  implements java.io.Serializable {


     private int idblog;
     private String blogTitle;
     private String blogContent;
     private String blogSummary;
     private String blogCreation;
     private String blogViews;
     private Set blogImageses = new HashSet(0);
     private Set blogCaptionses = new HashSet(0);

    public Blog() {
    }

	
    public Blog(int idblog) {
        this.idblog = idblog;
    }
    public Blog(int idblog, String blogTitle, String blogContent, String blogSummary, String blogCreation, String blogViews, Set blogImageses, Set blogCaptionses) {
       this.idblog = idblog;
       this.blogTitle = blogTitle;
       this.blogContent = blogContent;
       this.blogSummary = blogSummary;
       this.blogCreation = blogCreation;
       this.blogViews = blogViews;
       this.blogImageses = blogImageses;
       this.blogCaptionses = blogCaptionses;
    }
   
    public int getIdblog() {
        return this.idblog;
    }
    
    public void setIdblog(int idblog) {
        this.idblog = idblog;
    }
    public String getBlogTitle() {
        return this.blogTitle;
    }
    
    public void setBlogTitle(String blogTitle) {
        this.blogTitle = blogTitle;
    }
    public String getBlogContent() {
        return this.blogContent;
    }
    
    public void setBlogContent(String blogContent) {
        this.blogContent = blogContent;
    }
    public String getBlogSummary() {
        return this.blogSummary;
    }
    
    public void setBlogSummary(String blogSummary) {
        this.blogSummary = blogSummary;
    }
    public String getBlogCreation() {
        return this.blogCreation;
    }
    
    public void setBlogCreation(String blogCreation) {
        this.blogCreation = blogCreation;
    }
    public String getBlogViews() {
        return this.blogViews;
    }
    
    public void setBlogViews(String blogViews) {
        this.blogViews = blogViews;
    }
    public Set getBlogImageses() {
        return this.blogImageses;
    }
    
    public void setBlogImageses(Set blogImageses) {
        this.blogImageses = blogImageses;
    }
    public Set getBlogCaptionses() {
        return this.blogCaptionses;
    }
    
    public void setBlogCaptionses(Set blogCaptionses) {
        this.blogCaptionses = blogCaptionses;
    }




}


