package POJOs;
// Generated Feb 4, 2016 8:25:00 PM by Hibernate Tools 4.3.1



/**
 * ContactMessage generated by hbm2java
 */
public class ContactMessage  implements java.io.Serializable {


     private Integer idMessage;
     private String messageEmail;
     private String messageName;
     private String messageContent;

    public ContactMessage() {
    }

    public ContactMessage(String messageEmail, String messageName, String messageContent) {
       this.messageEmail = messageEmail;
       this.messageName = messageName;
       this.messageContent = messageContent;
    }
   
    public Integer getIdMessage() {
        return this.idMessage;
    }
    
    public void setIdMessage(Integer idMessage) {
        this.idMessage = idMessage;
    }
    public String getMessageEmail() {
        return this.messageEmail;
    }
    
    public void setMessageEmail(String messageEmail) {
        this.messageEmail = messageEmail;
    }
    public String getMessageName() {
        return this.messageName;
    }
    
    public void setMessageName(String messageName) {
        this.messageName = messageName;
    }
    public String getMessageContent() {
        return this.messageContent;
    }
    
    public void setMessageContent(String messageContent) {
        this.messageContent = messageContent;
    }




}


