package POJOs;
// Generated Feb 4, 2016 8:25:00 PM by Hibernate Tools 4.3.1



/**
 * DieseaseHasSymptom generated by hbm2java
 */
public class DieseaseHasSymptom  implements java.io.Serializable {


     private Integer idRule;
     private Diesease diesease;
     private Symptom symptom;

    public DieseaseHasSymptom() {
    }

    public DieseaseHasSymptom(Diesease diesease, Symptom symptom) {
       this.diesease = diesease;
       this.symptom = symptom;
    }
   
    public Integer getIdRule() {
        return this.idRule;
    }
    
    public void setIdRule(Integer idRule) {
        this.idRule = idRule;
    }
    public Diesease getDiesease() {
        return this.diesease;
    }
    
    public void setDiesease(Diesease diesease) {
        this.diesease = diesease;
    }
    public Symptom getSymptom() {
        return this.symptom;
    }
    
    public void setSymptom(Symptom symptom) {
        this.symptom = symptom;
    }




}


