package POJOs;
// Generated Feb 4, 2016 8:25:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Diesease generated by hbm2java
 */
public class Diesease  implements java.io.Serializable {


     private Integer iddiesease;
     private String dieseaseName;
     private String dieseaseDescription;
     private Set dieseaseHasSymptoms = new HashSet(0);

    public Diesease() {
    }

    public Diesease(String dieseaseName, String dieseaseDescription, Set dieseaseHasSymptoms) {
       this.dieseaseName = dieseaseName;
       this.dieseaseDescription = dieseaseDescription;
       this.dieseaseHasSymptoms = dieseaseHasSymptoms;
    }
   
    public Integer getIddiesease() {
        return this.iddiesease;
    }
    
    public void setIddiesease(Integer iddiesease) {
        this.iddiesease = iddiesease;
    }
    public String getDieseaseName() {
        return this.dieseaseName;
    }
    
    public void setDieseaseName(String dieseaseName) {
        this.dieseaseName = dieseaseName;
    }
    public String getDieseaseDescription() {
        return this.dieseaseDescription;
    }
    
    public void setDieseaseDescription(String dieseaseDescription) {
        this.dieseaseDescription = dieseaseDescription;
    }
    public Set getDieseaseHasSymptoms() {
        return this.dieseaseHasSymptoms;
    }
    
    public void setDieseaseHasSymptoms(Set dieseaseHasSymptoms) {
        this.dieseaseHasSymptoms = dieseaseHasSymptoms;
    }




}


