package POJOs;
// Generated Feb 4, 2016 8:25:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DoctorClasses generated by hbm2java
 */
public class DoctorClasses  implements java.io.Serializable {


     private Integer iddoctorClasses;
     private String className;
     private String classImage;
     private String classDescr;
     private Set doctorClassRequirementsHasDoctorClasseses = new HashSet(0);
     private Set doctorTemps = new HashSet(0);

    public DoctorClasses() {
    }

    public DoctorClasses(String className, String classImage, String classDescr, Set doctorClassRequirementsHasDoctorClasseses, Set doctorTemps) {
       this.className = className;
       this.classImage = classImage;
       this.classDescr = classDescr;
       this.doctorClassRequirementsHasDoctorClasseses = doctorClassRequirementsHasDoctorClasseses;
       this.doctorTemps = doctorTemps;
    }
   
    public Integer getIddoctorClasses() {
        return this.iddoctorClasses;
    }
    
    public void setIddoctorClasses(Integer iddoctorClasses) {
        this.iddoctorClasses = iddoctorClasses;
    }
    public String getClassName() {
        return this.className;
    }
    
    public void setClassName(String className) {
        this.className = className;
    }
    public String getClassImage() {
        return this.classImage;
    }
    
    public void setClassImage(String classImage) {
        this.classImage = classImage;
    }
    public String getClassDescr() {
        return this.classDescr;
    }
    
    public void setClassDescr(String classDescr) {
        this.classDescr = classDescr;
    }
    public Set getDoctorClassRequirementsHasDoctorClasseses() {
        return this.doctorClassRequirementsHasDoctorClasseses;
    }
    
    public void setDoctorClassRequirementsHasDoctorClasseses(Set doctorClassRequirementsHasDoctorClasseses) {
        this.doctorClassRequirementsHasDoctorClasseses = doctorClassRequirementsHasDoctorClasseses;
    }
    public Set getDoctorTemps() {
        return this.doctorTemps;
    }
    
    public void setDoctorTemps(Set doctorTemps) {
        this.doctorTemps = doctorTemps;
    }




}


