package POJOs;
// Generated Feb 4, 2016 8:25:00 PM by Hibernate Tools 4.3.1



/**
 * DoctorClassRequirementsHasDoctorClasses generated by hbm2java
 */
public class DoctorClassRequirementsHasDoctorClasses  implements java.io.Serializable {


     private Integer iddoctorClassRequirementsHasDoctorClasses;
     private DoctorClassRequirements doctorClassRequirements;
     private DoctorClasses doctorClasses;

    public DoctorClassRequirementsHasDoctorClasses() {
    }

    public DoctorClassRequirementsHasDoctorClasses(DoctorClassRequirements doctorClassRequirements, DoctorClasses doctorClasses) {
       this.doctorClassRequirements = doctorClassRequirements;
       this.doctorClasses = doctorClasses;
    }
   
    public Integer getIddoctorClassRequirementsHasDoctorClasses() {
        return this.iddoctorClassRequirementsHasDoctorClasses;
    }
    
    public void setIddoctorClassRequirementsHasDoctorClasses(Integer iddoctorClassRequirementsHasDoctorClasses) {
        this.iddoctorClassRequirementsHasDoctorClasses = iddoctorClassRequirementsHasDoctorClasses;
    }
    public DoctorClassRequirements getDoctorClassRequirements() {
        return this.doctorClassRequirements;
    }
    
    public void setDoctorClassRequirements(DoctorClassRequirements doctorClassRequirements) {
        this.doctorClassRequirements = doctorClassRequirements;
    }
    public DoctorClasses getDoctorClasses() {
        return this.doctorClasses;
    }
    
    public void setDoctorClasses(DoctorClasses doctorClasses) {
        this.doctorClasses = doctorClasses;
    }




}


