package POJOs;
// Generated Feb 4, 2016 8:25:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DoctorQualifications generated by hbm2java
 */
public class DoctorQualifications  implements java.io.Serializable {


     private Integer iddoctorQualifications;
     private String qualificationName;
     private String qualificationDescription;
     private Set doctorHasQualificationses = new HashSet(0);

    public DoctorQualifications() {
    }

    public DoctorQualifications(String qualificationName, String qualificationDescription, Set doctorHasQualificationses) {
       this.qualificationName = qualificationName;
       this.qualificationDescription = qualificationDescription;
       this.doctorHasQualificationses = doctorHasQualificationses;
    }
   
    public Integer getIddoctorQualifications() {
        return this.iddoctorQualifications;
    }
    
    public void setIddoctorQualifications(Integer iddoctorQualifications) {
        this.iddoctorQualifications = iddoctorQualifications;
    }
    public String getQualificationName() {
        return this.qualificationName;
    }
    
    public void setQualificationName(String qualificationName) {
        this.qualificationName = qualificationName;
    }
    public String getQualificationDescription() {
        return this.qualificationDescription;
    }
    
    public void setQualificationDescription(String qualificationDescription) {
        this.qualificationDescription = qualificationDescription;
    }
    public Set getDoctorHasQualificationses() {
        return this.doctorHasQualificationses;
    }
    
    public void setDoctorHasQualificationses(Set doctorHasQualificationses) {
        this.doctorHasQualificationses = doctorHasQualificationses;
    }




}


