package POJOs;
// Generated Feb 4, 2016 8:25:00 PM by Hibernate Tools 4.3.1



/**
 * DoctorHasQualifications generated by hbm2java
 */
public class DoctorHasQualifications  implements java.io.Serializable {


     private Integer idDoctorHasQualification;
     private Doctor doctor;
     private DoctorQualifications doctorQualifications;

    public DoctorHasQualifications() {
    }

    public DoctorHasQualifications(Doctor doctor, DoctorQualifications doctorQualifications) {
       this.doctor = doctor;
       this.doctorQualifications = doctorQualifications;
    }
   
    public Integer getIdDoctorHasQualification() {
        return this.idDoctorHasQualification;
    }
    
    public void setIdDoctorHasQualification(Integer idDoctorHasQualification) {
        this.idDoctorHasQualification = idDoctorHasQualification;
    }
    public Doctor getDoctor() {
        return this.doctor;
    }
    
    public void setDoctor(Doctor doctor) {
        this.doctor = doctor;
    }
    public DoctorQualifications getDoctorQualifications() {
        return this.doctorQualifications;
    }
    
    public void setDoctorQualifications(DoctorQualifications doctorQualifications) {
        this.doctorQualifications = doctorQualifications;
    }




}


