package POJOs;
// Generated Feb 4, 2016 8:25:00 PM by Hibernate Tools 4.3.1



/**
 * Grn generated by hbm2java
 */
public class Grn  implements java.io.Serializable {


     private int idGrn;
     private Medicine medicine;
     private Supplier supplier;
     private String qtySupplied;
     private String notes;
     private String date;

    public Grn() {
    }

	
    public Grn(int idGrn, Medicine medicine, Supplier supplier) {
        this.idGrn = idGrn;
        this.medicine = medicine;
        this.supplier = supplier;
    }
    public Grn(int idGrn, Medicine medicine, Supplier supplier, String qtySupplied, String notes, String date) {
       this.idGrn = idGrn;
       this.medicine = medicine;
       this.supplier = supplier;
       this.qtySupplied = qtySupplied;
       this.notes = notes;
       this.date = date;
    }
   
    public int getIdGrn() {
        return this.idGrn;
    }
    
    public void setIdGrn(int idGrn) {
        this.idGrn = idGrn;
    }
    public Medicine getMedicine() {
        return this.medicine;
    }
    
    public void setMedicine(Medicine medicine) {
        this.medicine = medicine;
    }
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    public String getQtySupplied() {
        return this.qtySupplied;
    }
    
    public void setQtySupplied(String qtySupplied) {
        this.qtySupplied = qtySupplied;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }




}


