package POJOs;
// Generated Feb 4, 2016 8:25:00 PM by Hibernate Tools 4.3.1



/**
 * Invoice generated by hbm2java
 */
public class Invoice  implements java.io.Serializable {


     private int idinvoice;
     private Patient patient;
     private Shipping shipping;
     private Double grossPrice;
     private Double netPrice;
     private String invoiceDate;

    public Invoice() {
    }

	
    public Invoice(int idinvoice, Patient patient, Shipping shipping) {
        this.idinvoice = idinvoice;
        this.patient = patient;
        this.shipping = shipping;
    }
    public Invoice(int idinvoice, Patient patient, Shipping shipping, Double grossPrice, Double netPrice, String invoiceDate) {
       this.idinvoice = idinvoice;
       this.patient = patient;
       this.shipping = shipping;
       this.grossPrice = grossPrice;
       this.netPrice = netPrice;
       this.invoiceDate = invoiceDate;
    }
   
    public int getIdinvoice() {
        return this.idinvoice;
    }
    
    public void setIdinvoice(int idinvoice) {
        this.idinvoice = idinvoice;
    }
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }
    public Shipping getShipping() {
        return this.shipping;
    }
    
    public void setShipping(Shipping shipping) {
        this.shipping = shipping;
    }
    public Double getGrossPrice() {
        return this.grossPrice;
    }
    
    public void setGrossPrice(Double grossPrice) {
        this.grossPrice = grossPrice;
    }
    public Double getNetPrice() {
        return this.netPrice;
    }
    
    public void setNetPrice(Double netPrice) {
        this.netPrice = netPrice;
    }
    public String getInvoiceDate() {
        return this.invoiceDate;
    }
    
    public void setInvoiceDate(String invoiceDate) {
        this.invoiceDate = invoiceDate;
    }




}


