package POJOs;
// Generated Dec 27, 2015 4:56:36 PM by Hibernate Tools 4.3.1



/**
 * InvoiceId generated by hbm2java
 */
public class InvoiceId  implements java.io.Serializable {


     private int idinvoice;
     private int patientIdpatient;

    public InvoiceId() {
    }

    public InvoiceId(int idinvoice, int patientIdpatient) {
       this.idinvoice = idinvoice;
       this.patientIdpatient = patientIdpatient;
    }
   
    public int getIdinvoice() {
        return this.idinvoice;
    }
    
    public void setIdinvoice(int idinvoice) {
        this.idinvoice = idinvoice;
    }
    public int getPatientIdpatient() {
        return this.patientIdpatient;
    }
    
    public void setPatientIdpatient(int patientIdpatient) {
        this.patientIdpatient = patientIdpatient;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InvoiceId) ) return false;
		 InvoiceId castOther = ( InvoiceId ) other; 
         
		 return (this.getIdinvoice()==castOther.getIdinvoice())
 && (this.getPatientIdpatient()==castOther.getPatientIdpatient());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdinvoice();
         result = 37 * result + this.getPatientIdpatient();
         return result;
   }   


}


