package POJOs;
// Generated Feb 4, 2016 8:25:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * MedicalServices generated by hbm2java
 */
public class MedicalServices  implements java.io.Serializable {


     private Integer idmedicalServices;
     private String serviceName;
     private String serviceDescription;
     private String serviceImage;
     private Double servicePrice;
     private Set timeTableServiceses = new HashSet(0);
     private Set patientHasMedicalservices = new HashSet(0);

    public MedicalServices() {
    }

    public MedicalServices(String serviceName, String serviceDescription, String serviceImage, Double servicePrice, Set timeTableServiceses, Set patientHasMedicalservices) {
       this.serviceName = serviceName;
       this.serviceDescription = serviceDescription;
       this.serviceImage = serviceImage;
       this.servicePrice = servicePrice;
       this.timeTableServiceses = timeTableServiceses;
       this.patientHasMedicalservices = patientHasMedicalservices;
    }
   
    public Integer getIdmedicalServices() {
        return this.idmedicalServices;
    }
    
    public void setIdmedicalServices(Integer idmedicalServices) {
        this.idmedicalServices = idmedicalServices;
    }
    public String getServiceName() {
        return this.serviceName;
    }
    
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }
    public String getServiceDescription() {
        return this.serviceDescription;
    }
    
    public void setServiceDescription(String serviceDescription) {
        this.serviceDescription = serviceDescription;
    }
    public String getServiceImage() {
        return this.serviceImage;
    }
    
    public void setServiceImage(String serviceImage) {
        this.serviceImage = serviceImage;
    }
    public Double getServicePrice() {
        return this.servicePrice;
    }
    
    public void setServicePrice(Double servicePrice) {
        this.servicePrice = servicePrice;
    }
    public Set getTimeTableServiceses() {
        return this.timeTableServiceses;
    }
    
    public void setTimeTableServiceses(Set timeTableServiceses) {
        this.timeTableServiceses = timeTableServiceses;
    }
    public Set getPatientHasMedicalservices() {
        return this.patientHasMedicalservices;
    }
    
    public void setPatientHasMedicalservices(Set patientHasMedicalservices) {
        this.patientHasMedicalservices = patientHasMedicalservices;
    }




}


