package POJOs;
// Generated Feb 4, 2016 8:25:00 PM by Hibernate Tools 4.3.1



/**
 * Misc generated by hbm2java
 */
public class Misc  implements java.io.Serializable {


     private Integer idmisc;
     private String imagePath;

    public Misc() {
    }

    public Misc(String imagePath) {
       this.imagePath = imagePath;
    }
   
    public Integer getIdmisc() {
        return this.idmisc;
    }
    
    public void setIdmisc(Integer idmisc) {
        this.idmisc = idmisc;
    }
    public String getImagePath() {
        return this.imagePath;
    }
    
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }




}


