package POJOs;
// Generated Feb 4, 2016 8:25:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Patient generated by hbm2java
 */
public class Patient  implements java.io.Serializable {


     private Integer idpatient;
     private String patientFname;
     private String patientMname;
     private String patientLname;
     private String patientAge;
     private String patientNic;
     private String patientPhoneno;
     private String patientEmail;
     private String patientAddress;
     private String patientDob;
     private String patientGender;
     private Set prescriptions = new HashSet(0);
     private Set timeTableServiceses = new HashSet(0);
     private Set users = new HashSet(0);
     private Set invoices = new HashSet(0);
     private Set patientHasMedicalservices = new HashSet(0);
     private Set appointments = new HashSet(0);

    public Patient() {
    }

    public Patient(String patientFname, String patientMname, String patientLname, String patientAge, String patientNic, String patientPhoneno, String patientEmail, String patientAddress, String patientDob, String patientGender, Set prescriptions, Set timeTableServiceses, Set users, Set invoices, Set patientHasMedicalservices, Set appointments) {
       this.patientFname = patientFname;
       this.patientMname = patientMname;
       this.patientLname = patientLname;
       this.patientAge = patientAge;
       this.patientNic = patientNic;
       this.patientPhoneno = patientPhoneno;
       this.patientEmail = patientEmail;
       this.patientAddress = patientAddress;
       this.patientDob = patientDob;
       this.patientGender = patientGender;
       this.prescriptions = prescriptions;
       this.timeTableServiceses = timeTableServiceses;
       this.users = users;
       this.invoices = invoices;
       this.patientHasMedicalservices = patientHasMedicalservices;
       this.appointments = appointments;
    }
   
    public Integer getIdpatient() {
        return this.idpatient;
    }
    
    public void setIdpatient(Integer idpatient) {
        this.idpatient = idpatient;
    }
    public String getPatientFname() {
        return this.patientFname;
    }
    
    public void setPatientFname(String patientFname) {
        this.patientFname = patientFname;
    }
    public String getPatientMname() {
        return this.patientMname;
    }
    
    public void setPatientMname(String patientMname) {
        this.patientMname = patientMname;
    }
    public String getPatientLname() {
        return this.patientLname;
    }
    
    public void setPatientLname(String patientLname) {
        this.patientLname = patientLname;
    }
    public String getPatientAge() {
        return this.patientAge;
    }
    
    public void setPatientAge(String patientAge) {
        this.patientAge = patientAge;
    }
    public String getPatientNic() {
        return this.patientNic;
    }
    
    public void setPatientNic(String patientNic) {
        this.patientNic = patientNic;
    }
    public String getPatientPhoneno() {
        return this.patientPhoneno;
    }
    
    public void setPatientPhoneno(String patientPhoneno) {
        this.patientPhoneno = patientPhoneno;
    }
    public String getPatientEmail() {
        return this.patientEmail;
    }
    
    public void setPatientEmail(String patientEmail) {
        this.patientEmail = patientEmail;
    }
    public String getPatientAddress() {
        return this.patientAddress;
    }
    
    public void setPatientAddress(String patientAddress) {
        this.patientAddress = patientAddress;
    }
    public String getPatientDob() {
        return this.patientDob;
    }
    
    public void setPatientDob(String patientDob) {
        this.patientDob = patientDob;
    }
    public String getPatientGender() {
        return this.patientGender;
    }
    
    public void setPatientGender(String patientGender) {
        this.patientGender = patientGender;
    }
    public Set getPrescriptions() {
        return this.prescriptions;
    }
    
    public void setPrescriptions(Set prescriptions) {
        this.prescriptions = prescriptions;
    }
    public Set getTimeTableServiceses() {
        return this.timeTableServiceses;
    }
    
    public void setTimeTableServiceses(Set timeTableServiceses) {
        this.timeTableServiceses = timeTableServiceses;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }
    public Set getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set invoices) {
        this.invoices = invoices;
    }
    public Set getPatientHasMedicalservices() {
        return this.patientHasMedicalservices;
    }
    
    public void setPatientHasMedicalservices(Set patientHasMedicalservices) {
        this.patientHasMedicalservices = patientHasMedicalservices;
    }
    public Set getAppointments() {
        return this.appointments;
    }
    
    public void setAppointments(Set appointments) {
        this.appointments = appointments;
    }




}


