package POJOs;
// Generated Feb 4, 2016 8:25:00 PM by Hibernate Tools 4.3.1



/**
 * PatientHasMedicalservice generated by hbm2java
 */
public class PatientHasMedicalservice  implements java.io.Serializable {


     private Integer patientMedicalId;
     private MedicalServices medicalServices;
     private Patient patient;
     private String appintmentDate;

    public PatientHasMedicalservice() {
    }

	
    public PatientHasMedicalservice(MedicalServices medicalServices, Patient patient) {
        this.medicalServices = medicalServices;
        this.patient = patient;
    }
    public PatientHasMedicalservice(MedicalServices medicalServices, Patient patient, String appintmentDate) {
       this.medicalServices = medicalServices;
       this.patient = patient;
       this.appintmentDate = appintmentDate;
    }
   
    public Integer getPatientMedicalId() {
        return this.patientMedicalId;
    }
    
    public void setPatientMedicalId(Integer patientMedicalId) {
        this.patientMedicalId = patientMedicalId;
    }
    public MedicalServices getMedicalServices() {
        return this.medicalServices;
    }
    
    public void setMedicalServices(MedicalServices medicalServices) {
        this.medicalServices = medicalServices;
    }
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }
    public String getAppintmentDate() {
        return this.appintmentDate;
    }
    
    public void setAppintmentDate(String appintmentDate) {
        this.appintmentDate = appintmentDate;
    }




}


