package POJOs;
// Generated Feb 4, 2016 8:25:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Prescription generated by hbm2java
 */
public class Prescription  implements java.io.Serializable {


     private Integer idprescription;
     private Doctor doctor;
     private Patient patient;
     private String prescriptionStartdate;
     private String prescriptionEnddate;
     private String prescriptionStatus;
     private Set prescriptionHasMedicines = new HashSet(0);

    public Prescription() {
    }

	
    public Prescription(Doctor doctor, Patient patient) {
        this.doctor = doctor;
        this.patient = patient;
    }
    public Prescription(Doctor doctor, Patient patient, String prescriptionStartdate, String prescriptionEnddate, String prescriptionStatus, Set prescriptionHasMedicines) {
       this.doctor = doctor;
       this.patient = patient;
       this.prescriptionStartdate = prescriptionStartdate;
       this.prescriptionEnddate = prescriptionEnddate;
       this.prescriptionStatus = prescriptionStatus;
       this.prescriptionHasMedicines = prescriptionHasMedicines;
    }
   
    public Integer getIdprescription() {
        return this.idprescription;
    }
    
    public void setIdprescription(Integer idprescription) {
        this.idprescription = idprescription;
    }
    public Doctor getDoctor() {
        return this.doctor;
    }
    
    public void setDoctor(Doctor doctor) {
        this.doctor = doctor;
    }
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }
    public String getPrescriptionStartdate() {
        return this.prescriptionStartdate;
    }
    
    public void setPrescriptionStartdate(String prescriptionStartdate) {
        this.prescriptionStartdate = prescriptionStartdate;
    }
    public String getPrescriptionEnddate() {
        return this.prescriptionEnddate;
    }
    
    public void setPrescriptionEnddate(String prescriptionEnddate) {
        this.prescriptionEnddate = prescriptionEnddate;
    }
    public String getPrescriptionStatus() {
        return this.prescriptionStatus;
    }
    
    public void setPrescriptionStatus(String prescriptionStatus) {
        this.prescriptionStatus = prescriptionStatus;
    }
    public Set getPrescriptionHasMedicines() {
        return this.prescriptionHasMedicines;
    }
    
    public void setPrescriptionHasMedicines(Set prescriptionHasMedicines) {
        this.prescriptionHasMedicines = prescriptionHasMedicines;
    }




}


