package POJOs;
// Generated Feb 4, 2016 8:25:00 PM by Hibernate Tools 4.3.1



/**
 * PrescriptionHasMedicine generated by hbm2java
 */
public class PrescriptionHasMedicine  implements java.io.Serializable {


     private Integer idPrescriptioHasMedicine;
     private Medicine medicine;
     private Prescription prescription;
     private String directionUse;

    public PrescriptionHasMedicine() {
    }

	
    public PrescriptionHasMedicine(Medicine medicine, Prescription prescription) {
        this.medicine = medicine;
        this.prescription = prescription;
    }
    public PrescriptionHasMedicine(Medicine medicine, Prescription prescription, String directionUse) {
       this.medicine = medicine;
       this.prescription = prescription;
       this.directionUse = directionUse;
    }
   
    public Integer getIdPrescriptioHasMedicine() {
        return this.idPrescriptioHasMedicine;
    }
    
    public void setIdPrescriptioHasMedicine(Integer idPrescriptioHasMedicine) {
        this.idPrescriptioHasMedicine = idPrescriptioHasMedicine;
    }
    public Medicine getMedicine() {
        return this.medicine;
    }
    
    public void setMedicine(Medicine medicine) {
        this.medicine = medicine;
    }
    public Prescription getPrescription() {
        return this.prescription;
    }
    
    public void setPrescription(Prescription prescription) {
        this.prescription = prescription;
    }
    public String getDirectionUse() {
        return this.directionUse;
    }
    
    public void setDirectionUse(String directionUse) {
        this.directionUse = directionUse;
    }




}


