package POJOs;
// Generated Feb 4, 2016 8:25:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Supplier generated by hbm2java
 */
public class Supplier  implements java.io.Serializable {


     private Integer idsupplier;
     private String supplierFname;
     private String supplierMname;
     private String supplierLname;
     private String supplierAddress;
     private String supplierOrganizationName;
     private String supplierLand;
     private String supplierPhone;
     private String supplierNic;
     private Set medicines = new HashSet(0);
     private Set grns = new HashSet(0);

    public Supplier() {
    }

    public Supplier(String supplierFname, String supplierMname, String supplierLname, String supplierAddress, String supplierOrganizationName, String supplierLand, String supplierPhone, String supplierNic, Set medicines, Set grns) {
       this.supplierFname = supplierFname;
       this.supplierMname = supplierMname;
       this.supplierLname = supplierLname;
       this.supplierAddress = supplierAddress;
       this.supplierOrganizationName = supplierOrganizationName;
       this.supplierLand = supplierLand;
       this.supplierPhone = supplierPhone;
       this.supplierNic = supplierNic;
       this.medicines = medicines;
       this.grns = grns;
    }
   
    public Integer getIdsupplier() {
        return this.idsupplier;
    }
    
    public void setIdsupplier(Integer idsupplier) {
        this.idsupplier = idsupplier;
    }
    public String getSupplierFname() {
        return this.supplierFname;
    }
    
    public void setSupplierFname(String supplierFname) {
        this.supplierFname = supplierFname;
    }
    public String getSupplierMname() {
        return this.supplierMname;
    }
    
    public void setSupplierMname(String supplierMname) {
        this.supplierMname = supplierMname;
    }
    public String getSupplierLname() {
        return this.supplierLname;
    }
    
    public void setSupplierLname(String supplierLname) {
        this.supplierLname = supplierLname;
    }
    public String getSupplierAddress() {
        return this.supplierAddress;
    }
    
    public void setSupplierAddress(String supplierAddress) {
        this.supplierAddress = supplierAddress;
    }
    public String getSupplierOrganizationName() {
        return this.supplierOrganizationName;
    }
    
    public void setSupplierOrganizationName(String supplierOrganizationName) {
        this.supplierOrganizationName = supplierOrganizationName;
    }
    public String getSupplierLand() {
        return this.supplierLand;
    }
    
    public void setSupplierLand(String supplierLand) {
        this.supplierLand = supplierLand;
    }
    public String getSupplierPhone() {
        return this.supplierPhone;
    }
    
    public void setSupplierPhone(String supplierPhone) {
        this.supplierPhone = supplierPhone;
    }
    public String getSupplierNic() {
        return this.supplierNic;
    }
    
    public void setSupplierNic(String supplierNic) {
        this.supplierNic = supplierNic;
    }
    public Set getMedicines() {
        return this.medicines;
    }
    
    public void setMedicines(Set medicines) {
        this.medicines = medicines;
    }
    public Set getGrns() {
        return this.grns;
    }
    
    public void setGrns(Set grns) {
        this.grns = grns;
    }




}


