package POJOs;
// Generated Feb 4, 2016 8:25:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer iduser;
     private Administrator administrator;
     private Doctor doctor;
     private Patient patient;
     private String username;
     private String password;
     private String usertype;
     private Set blogCaptionses = new HashSet(0);
     private Set blogReplies = new HashSet(0);

    public User() {
    }

	
    public User(Administrator administrator, Doctor doctor, Patient patient) {
        this.administrator = administrator;
        this.doctor = doctor;
        this.patient = patient;
    }
    public User(Administrator administrator, Doctor doctor, Patient patient, String username, String password, String usertype, Set blogCaptionses, Set blogReplies) {
       this.administrator = administrator;
       this.doctor = doctor;
       this.patient = patient;
       this.username = username;
       this.password = password;
       this.usertype = usertype;
       this.blogCaptionses = blogCaptionses;
       this.blogReplies = blogReplies;
    }
   
    public Integer getIduser() {
        return this.iduser;
    }
    
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }
    public Administrator getAdministrator() {
        return this.administrator;
    }
    
    public void setAdministrator(Administrator administrator) {
        this.administrator = administrator;
    }
    public Doctor getDoctor() {
        return this.doctor;
    }
    
    public void setDoctor(Doctor doctor) {
        this.doctor = doctor;
    }
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getUsertype() {
        return this.usertype;
    }
    
    public void setUsertype(String usertype) {
        this.usertype = usertype;
    }
    public Set getBlogCaptionses() {
        return this.blogCaptionses;
    }
    
    public void setBlogCaptionses(Set blogCaptionses) {
        this.blogCaptionses = blogCaptionses;
    }
    public Set getBlogReplies() {
        return this.blogReplies;
    }
    
    public void setBlogReplies(Set blogReplies) {
        this.blogReplies = blogReplies;
    }




}


